#include <string>
#include <vector>

std::vector<int> MON_ANIM_HACK_LIST = std::vector<int>(683,0);
std::vector<bool> MON_ROT_HACK_LIST = std::vector<bool>(683,false);

std::vector<std::string> MON_NAMES_LIST = {"Blue-Eyes White Dragon",
    "Seiyaryu",
    "Blue-Eyes Ultimate Dragon",
    "Kaiser Dragon",
    "Blackland Fire Dragon",
    "Koumori Dragon",
    "Curse of Dragon",
    "Red-Eyes B. Dragon",
    "Darkfire Dragon",
    "B. Skull Dragon",
    "Tri-Horned Dragon",
    "Serpent Night Dragon",
    "Mikozukinoyaiba",
    "Yamadron",
    "Meteor B. Dragon",
    "Tyhone #2",
    "Ryu-Ran",
    "Manga Ryu-Ran",
    "Crawling Dragon",
    "Meteor Dragon",
    "B. Dragon Jungle King",
    "Baby Dragon",
    "Winged Dragon, Guardian of Fortress #1",
    "Gaia the Dragon Champion",
    "Thousand Dragon",
    "Yamatano Dragon Scroll",
    "Petit Dragon",
    "One-Eyed Shield Dragon",
    "Wicked Dragon with the Ersatz Head",
    "Parrot Dragon",
    "Harpie's Pet Dragon",
    "Sky Dragon",
    "Lesser Dragon",
    "Fairy Dragon",
    "Twin-Headed Behemoth",
    "Mystical Elf",
    "Time Wizard",
    "Rogue Doll",
    "White Magical Hat",
    "La Moon",
    "Lucky Trinket",
    "Genin",
    "Fairy's Gift",
    "Magician of Faith",
    "Ancient Elf",
    "Maha Vailo",
    "Musician King",
    "Eldeen",
    "Lady of Faith",
    "Ill Witch",
    "Maiden of the Moonlight",
    "The Stern Mystic",
    "Neo the Magical Swordsman",
    "The Unhappy Maiden",
    "Right Leg of the Forbidden One",
    "Left Leg of the Forbidden One",
    "Right Arm of the Forbidden One",
    "Left Arm of the Forbidden One",
    "Exodia the Forbidden One",
    "Saggi the Dark Clown",
    "Dark Magician",
    "Illusionist Faceless Mage",
    "Curtain of the Dark Ones",
    "Kamionwizard",
    "Nemuriko",
    "Necrolancer the Timelord",
    "The Bewitching Phantom Thief",
    "Phantom Dewan",
    "Akakieisu",
    "Masked Sorceror",
    "Fairy Witch",
    "Ancient Sorceror",
    "Sectarian of Secrets",
    "Mystic Lamp",
    "Boo Koo",
    "Skull Knight",
    "Cosmo Queen",
    "Mask of Shine & Dark",
    "Magician of Black Chaos",
    "Dark Elf",
    "Witch of the Black Forest",
    "Witch's Apprentice",
    "Sorceror of the Doomed",
    "Lord of D.",
    "Invitation to a Dark Sleep",
    "Hannibal Necromancer",
    "The Illusory Gentleman",
    "Dark Magician Girl",
    "Flame Manipulator",
    "Dryad",
    "Tao the Chanter",
    "Spirit of the Mountain",
    "Gemini Elf",
    "Leo Wizard",
    "Rock Spirit",
    "Injection Fairy Lily",
    "Spirit of the Winds",
    "Djinn the Watcher of the Wind",
    "Hurricail",
    "Kazejin",
    "Aqua Madoor",
    "Shadow Spectre",
    "Skull Servant",
    "Zombie Warrior",
    "The Snake Hair",
    "Armored Zombie",
    "Dragon Zombie",
    "Clown Zombie",
    "Pumpking the King of Ghosts",
    "Graveyard and the Hand of Invitation",
    "The 13th Grave",
    "Fiend's Hand",
    "Blue-Eyed Silver Zombie",
    "Temple of Skulls",
    "Dokuroizo the Grim Reaper",
    "Fire Reaper",
    "Mech Mole Zombie",
    "Phantom Ghost",
    "Flame Ghost",
    "Wood Remains",
    "Dark Assailant",
    "Yaranzo",
    "Three Legged Zombies",
    "Shadow Ghoul",
    "Magical Ghost",
    "Corroding Shark",
    "Skelgon",
    "Bone Mouse",
    "Dokurorider",
    "The Wandering Doomed",
    "Grand Mammoth of Goldfine",
    "Ghoul with an Appetite",
    "Patrician of Darkness",
    "Moon Envoy",
    "Giltia the D. Knight",
    "Skull Guardian",
    "Luminous Soldier",
    "Kageningen",
    "Masked Clown",
    "Fiend Sword",
    "Skull Stalker",
    "Vishwar Randi",
    "Unknown Warrior of Fiend",
    "Black Luster Soldier",
    "Wall Shadow",
    "Gate Guardian",
    "Swordstalker",
    "Hungry Burger",
    "Garma Sword",
    "Greenkappa",
    "Succubus Knight",
    "Flaming Swordsman",
    "Tactical Warrior",
    "Swamp Battleguard",
    "Judge Man",
    "Gaia the Fierce Knight",
    "Celtic Guardian",
    "Karbonala Warrior",
    "Kojicocy",
    "Axe Raider",
    "Zanki",
    "Battle Warrior",
    "Hero of the East",
    "Supporter in the Shadows",
    "Dream Clown",
    "Ansatsu",
    "Dragon Statue",
    "Monster Egg",
    "Rhaimundos of the Red Sword",
    "Hard Armor",
    "M-Warrior #1",
    "M-Warrior #2",
    "Judgement Hand",
    "Mysterious Puppeteer",
    "Armaill",
    "Eyearmor",
    "Doron",
    "Kagemusha of the Blue Flame",
    "Trap Master",
    "Wood Clown",
    "Beautiful Headhuntress",
    "Wodan the Resident of the Forest",
    "Guardian of the Labyrinth",
    "Dimensional Warrior",
    "Protector of the Throne",
    "Masaki the Legendary Swordsman",
    "Sonic Maid",
    "Kanan the Swordmistress",
    "Stuffed Animal",
    "Millennium Shield",
    "Monster Tamer",
    "Swordsman from a Foreign Land",
    "Beautiful Beast Trainer",
    "Armed Ninja",
    "D. Human",
    "Performance of Sword",
    "Mushroom Man #2",
    "Lava Battleguard",
    "Oscillo Hero",
    "Empress Judge",
    "Warrior of Tradition",
    "Queen's Double",
    "Invader of the Throne",
    "Hibikime",
    "Princess of Tsurugi",
    "Dragoness the Wicked Knight",
    "Hyo",
    "The Little Swordsman of Aile",
    "Garoozis",
    "Hitotsu-Me Giant",
    "Battle Steer",
    "Battle Ox",
    "Beaver Warrior",
    "Mountain Warrior",
    "Tiger Axe",
    "Rabid Horseman",
    "Solitude",
    "One Who Hunts Souls",
    "Ogre of the Black Shadow",
    "Rude Kaiser",
    "Sengenjin",
    "Nekogal #2",
    "Panther Warrior",
    "Wolf Axewielder",
    "Gate Deeg",
    "Dark Rabbit",
    "Firewing Pegasus",
    "Little Chimera",
    "The Wicked Worm Beast",
    "Griffore",
    "Torike",
    "Wolf",
    "Silver Fang",
    "Mystic Horseman",
    "Dark Gray",
    "Sleeping Lion",
    "Larvas",
    "Dig Beak",
    "Lisark",
    "Synchar",
    "Fusionist",
    "Frenzied Panda",
    "Air Marmot of Nefariousness",
    "Meotoko",
    "Master & Expert",
    "Nekogal #1",
    "Prevent Rat",
    "Mystical Sheep #2",
    "Super War Lion",
    "Leogun",
    "Tatsunootoshigo",
    "Burglar",
    "Garvas",
    "Flower Wolf",
    "Armored Rat",
    "Milus Radiant",
    "Togex",
    "Hane Hane",
    "Ancient One of the Deep Forest",
    "Mon Larvas",
    "Pale Beast",
    "Obese Marmot of Nefariousness",
    "Great Bill",
    "Armored Rat",
    "Mystical Sheep",
    "Gazelle the King of Mythical Beasts",
    "King Tiger Wanghu",
    "Chimera the Flying Mythical Beast",
    "Fiend Reflection #2",
    "Crimson Sunbird",
    "Niwatori",
    "Tyhone",
    "Harpie Lady",
    "Harpie Lady Sisters",
    "Spirit of the Books",
    "Faith Bird",
    "Droll Bird",
    "Mavelus",
    "Kurama",
    "Wing Eagle",
    "Punished Eagle",
    "Skull Red Bird",
    "Queen Bird",
    "Peacock",
    "Skullbird",
    "Monstrous Bird",
    "Winged Dragon, Guardian of Fortress #2",
    "Crow Goblin",
    "Takuhee",
    "Fiend Reflection #1",
    "Blue-Winged Crown",
    "Birdface",
    "Ryu-Kishin",
    "Feral Imp",
    "Summoned Skull",
    "Horn Imp",
    "Sangan",
    "Kuriboh",
    "Castle of Dark Illusions",
    "Reaper of the Cards",
    "King of Yamimakai",
    "Barox",
    "Dark Chimera",
    "Metal Guardian",
    "Crass Clown",
    "Mask of Darkness",
    "Job Change Mirror",
    "That Which Feeds on Life",
    "Trial of Nightmare",
    "Witty Phantom",
    "Mystery Hand",
    "The Shadow Who Controls the Dark",
    "Lord of the Lamp",
    "Tainted Wisdom",
    "Lord of Zemia",
    "Dark King of the Abyss",
    "Big Eye",
    "Dark Prisoner",
    "Ancient Brain",
    "Claw Reacher",
    "Terra the Terrible",
    "Mabarrel",
    "Midnight Fiend",
    "Madjinn Gunn",
    "Dark Titan of Terror",
    "The Drdek",
    "Candle of Fate",
    "Meda Bat",
    "Embryonic Beast",
    "Wicked Mirror",
    "Versago the Destroyer",
    "Megirus Light",
    "Gorgon Egg",
    "King Fog",
    "Mystic Clown",
    "Dark Artist",
    "Bio Plant",
    "Zera the Mant",
    "Fiend's Mirror",
    "Ryu-Kishin Powered",
    "La Jinn the Mystical Genie of Lamp",
    "Bickuribox",
    "Zoa",
    "Ushi Oni",
    "Monster Eye",
    "Soul Hunter",
    "Needle Ball",
    "Morinphen",
    "Dragon Seeker",
    "Fungi of the Musk",
    "Bistro Butcher",
    "Neck Hunter",
    "Chakra",
    "Psycho Puppet",
    "Invader from Another Dimension",
    "Wretched Ghost of the Attic",
    "Key Mace #2",
    "Hiro's Shadow Scout",
    "Whiptail Crow",
    "Man-Eating Treasure Chest",
    "Baron of the Fiend Sword",
    "Wall of Illusion",
    "Toon Summoned Skull",
    "Three-Headed Geedo",
    "Berfomet",
    "Kryuel",
    "Dark Shade",
    "Air Eater",
    "Gyakutenno Megami",
    "Goddess with the Third Eye",
    "Orion the Battle King",
    "Weather Control",
    "Mystical Capture Chain",
    "Spirit of the Harp",
    "Key Mace",
    "Happy Lover",
    "Petit Angel",
    "Hourglass of Life",
    "Lunar Queen Elzaim",
    "Wing Egg Elf",
    "Ray & Temperature",
    "Ocubeam",
    "Goddess of Whim",
    "Hoshiningen",
    "Skelengel",
    "Dark Witch",
    "Binding Chain",
    "Muse-A",
    "Tenderness",
    "Shining Friendship",
    "Hourglass of Courage",
    "Winged Egg of New Life",
    "Airknight Parshath",
    "Doma the Angel of Silence",
    "Dancing Elf",
    "Spiked Snail",
    "Big Insect",
    "Basic Insect",
    "Hercules Beetle",
    "Gokibore",
    "Giant Flea",
    "Larvae Moth",
    "Great Moth",
    "Perfectly Ultimate Great Moth",
    "Nightmare Scorpion",
    "Winged Cleaver",
    "Kumootuko",
    "Petit Moth",
    "Jirai Gumo",
    "Dungeon Worm",
    "Leghul",
    "Ganigumo",
    "Alinsection",
    "Cockroach Knight",
    "Kuwagata Alpha",
    "Korogashi",
    "Kattapillar",
    "Man-Eater Bug",
    "Gale Dogra",
    "Kwagar Hercules",
    "Minar",
    "Kamakiriman",
    "Javelin Beetle",
    "Needle Worm",
    "Giant Scorpion of the Tundra",
    "Hunter Spider",
    "Acid Crawler",
    "Larva of Moth",
    "Pupa of Moth",
    "Arsenal Bug",
    "Killer Needle",
    "Insect Soldiers of the Sky",
    "Bladefly",
    "Sword Arm of Dragon",
    "Two-Headed King Rex",
    "Mammoth Graveyard",
    "Megazowler",
    "Uraby",
    "Crawling Dragon #2",
    "Tomozaurus",
    "Two-Mouth Darkruler",
    "Pragtical",
    "Anthrosaurus",
    "Trakodon",
    "Little D",
    "Bracchio-raidus",
    "Armored Lizard",
    "Serpent Marauder",
    "Yormungarde",
    "Drooling Lizard",
    "Beaked Snake",
    "Ancient Lizard Warrior",
    "Krokodilus",
    "Grappler",
    "Toon Alligator",
    "Emperor of the Land and Sea",
    "Sinister Serpent",
    "Mechaleon",
    "Serpentine Princess",
    "Great White",
    "Rare Fish",
    "Root Water",
    "Enchanting Mermaid",
    "White Dolphin",
    "Deepsea Shark",
    "Bottom Dweller",
    "7 Colored Fish",
    "Rainbow Marine Mermaid",
    "Crazy Fish",
    "Misairuzame",
    "Tongyo",
    "Wow Warrior",
    "Fortress Whale",
    "Man-Eating Black Shark",
    "Marine Beast",
    "Amazon of the Seas",
    "Kairyu-Shin",
    "Takriminos",
    "Aqua Dragon",
    "Sea King Dragon",
    "Spike Seadra",
    "Guardian of the Throne Room",
    "Ancient Tool",
    "Gate Keeper",
    "Cyber Soldier of Darkworld",
    "Megasonic Eye",
    "Labyrinth Tank",
    "Pendulum Machine",
    "Metalzoa",
    "Saber Slasher",
    "Yaiba Robo",
    "Cyber Soldier",
    "Mechanical Chaser",
    "Blocker",
    "Spike Clubber",
    "Cyber-Stein",
    "Cyber Commander",
    "Jinzo #7",
    "Cannon Soldier",
    "Brave Scizzar",
    "Dharma Cannon",
    "Red-Eyes Black Metal Dragon",
    "Barrel Dragon",
    "Mechanical Snail",
    "Disk Magician",
    "Slot Machine",
    "Blast Sphere",
    "Space Megatron",
    "Launcher Spider",
    "Blast Juggler",
    "Robotic Knight",
    "Ground Attacker Bugroth",
    "Holograh",
    "Steel Scorpion",
    "Machine King",
    "Giant Mech Soldier",
    "Mechanical Spider",
    "Giga-tech Wolf",
    "Shovel Crusher",
    "Golgoil",
    "Dice Armadillo",
    "Cyber Saurus",
    "Steel Ogre Grotto",
    "Patrol Robo",
    "Royal Guard",
    "Machine Attacker",
    "Steel Ogre Grotto #2",
    "Gear Golem the Moving Fortress",
    "Kinetic Soldier",
    "Metal Dragon",
    "Bat",
    "Metal Fish",
    "Mech Bass",
    "Oscillo Hero #2",
    "Sanga of the Thunder",
    "Thunder Dragon",
    "The Immortal of Thunder",
    "Electric Snake",
    "Twin-Headed Thunder Dragon",
    "Thunder Nyan Nyan",
    "Tripwire Beast",
    "Electric Lizard",
    "La Li-Oon",
    "Kaminarikozou",
    "Kaminari Attack",
    "Mega Thunderball",
    "Bolt Escargo",
    "Bolt Penguin",
    "Fire Kraken",
    "Boulder Tortoise",
    "Fiend Kraken",
    "Jellyfish",
    "Catapult Turtle",
    "Octoberser",
    "Toad Master",
    "Akihiron",
    "The Melting Red Shadow",
    "Monsturtle",
    "Turtle Tiger",
    "Arma Knight",
    "Penguin Knight",
    "Dorover",
    "Twin Long Rods #1",
    "Roaring Ocean Snake",
    "Hitodenchak",
    "Water Element",
    "Water Omotics",
    "Beastking of the Swamps",
    "The Furious Sea King",
    "Wetha",
    "Change Slime",
    "Psychic Kappa",
    "Flying Penguin",
    "Suijin",
    "Zone Eater",
    "Ooguchi",
    "Water Magician",
    "Ice Water",
    "Waterdragon Fairy",
    "Water Girl",
    "Turu-Purun",
    "Guardian of the Sea",
    "Aqua Snake",
    "Giant Red Seasnake",
    "30,000 Year White Turtle",
    "Kappa Avenger",
    "Kanikabuto",
    "Zarigun",
    "Sea Kamen",
    "Ameba",
    "Yado Karu",
    "Turtle Raccoon",
    "Turtle Bird",
    "Star Boy",
    "Frog the Jam",
    "Behegon",
    "Crab Turtle",
    "Weather Report",
    "Giant Turtle Who Feeds on Flames",
    "Violent Rain",
    "Penguin Soldier",
    "Liquid Beast",
    "Twin Long Rods #2",
    "Armored Starfish",
    "High Tide Gyojin",
    "Fairy of the Fountain",
    "Night Lizard",
    "Amphibious Bugroth",
    "Gruesome Goo",
    "Hyosube",
    "Red Archery Girl",
    "Toon Mermaid",
    "Maiden of the Aqua",
    "Dragon Piper",
    "Wings of Wicked Flame",
    "Charubin the Fire Knight",
    "Fire Eye",
    "Hinotama Soul",
    "Fireyarou",
    "Vermillion Sparrow",
    "Flame Cerebrus",
    "Jigen Bakudan",
    "Molten Behemoth",
    "Flame Snake",
    "Prisman",
    "Rock Ogre Grotto #1",
    "Giant Soldier of Stone",
    "Ancient Jar",
    "Haniwa",
    "Dissolverock",
    "Stone Armadiller",
    "Rock Ogre Grotto #2",
    "Stone D.",
    "Millennium Golem",
    "Destroyer Golem",
    "Barrel Rock",
    "Minomushi Warrior",
    "Stone Ghost",
    "The Statue of Easter Island",
    "Muka Muka",
    "Sand Stone",
    "Mystical Sand",
    "Pot the Trick",
    "Morphing Jar",
    "The Thing That Hides in the Mud",
    "Stone Ogre Grotto",
    "Stone Statue of the Aztecs",
    "Dark Plant",
    "Rose Spectre of Dunn",
    "Mushroom Man",
    "Man-Eating Plant",
    "Firegrass",
    "Man Eater",
    "Arlownay",
    "Yashinoki",
    "Ancient Tree of Enlightenment",
    "Green Phantom King",
    "Rainbow Flower",
    "Barrel Lily",
    "Laughing Flower",
    "Bean Soldier",
    "Griggle",
    "Darkworld Thorns",
    "Abyss Flower",
    "Living Vase",
    "Snakeyashi",
    "Trent",
    "Queen of Autumn Leaves",
    "Woodland Sprite",
    "Tentacle Plant",
    "Fairy King Truesdale",
    "Summoned Lord Exodia",
    "Jowls of Dark Demise",
    "Souleater",
    "Slate Warrior",
    "Shapesnatch",
    "Carat Idol",
    "Electromagnetic Bagworm",
    "Time Eater",
    "Mucus Yolk",
    "Servant of Catabolism",
    "Rigras Leever",
    "Moisture Creature"};